INSERT INTO `mas`.`CABINCLASS` (`DELETED`,`NAME`,`TYPE`)
VALUES(0, 'Merlion Sky Palace','F');

INSERT INTO `mas`.`CABINCLASS` (`DELETED`,`NAME`,`TYPE`)
VALUES(0, 'Business','B');

INSERT INTO `mas`.`CABINCLASS` (`DELETED`,`NAME`,`TYPE`)
VALUES(0, 'Premium Economy','P');

INSERT INTO `mas`.`CABINCLASS` (`DELETED`,`NAME`,`TYPE`)
VALUES(0, 'Economy','E');

INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (16.91,140640,0.86,440,275,180,'Airbus',63.69,13500,10.69,'A340-300','A340 Family',277,25.6,60.3);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.05,138000,0.89,440,248,178,'Airbus',60.54,15200,10.6,'A350-800','A350 XWB',280,24.86,64.75);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.05,138000,0.89,440,268,192,'Airbus',66.8,14350,10.6,'A350-900','A350 XWB',325,28.67,64.75);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.22,195520,0.86,475,368,245,'Airbus',75.36,14450,10.69,'A340-600','A340 Family',326,32.89,63.45);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (16.83,97530,0.86,440,230,173,'Airbus',63.69,11750,10.69,'A330-300','A330 Family',277,25.6,60.3);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (11.76,24210,0.82,156,64,57,'Airbus',33.84,6850,7.59,'A319','A320 Family',124,11.04,35.8);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (11.76,24210,0.82,180,73.5,61,'Airbus',37.57,6100,7.59,'A320','A320 Family',150,12.64,35.8);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (12.56,24210,0.82,132,59,53,'Airbus',31.44,5750,7.59,'A318','A320 Family',107,10.25,34.1);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.08,156000,0.89,440,308,220,'Airbus',73.78,14800,10.73,'A350-1000','A350 XWB',366,32.48,64.75);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (24.09,320000,0.89,853,575,369,'Airbus',72.72,15200,14.34,'A380','A380',544,31.88,79.75);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.39,139090,0.86,406,230,168,'Airbus',58.82,13450,10.69,'A330-200','A330 Family',247,22.2,60.3);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (11.76,24050,0.82,236,89,71.5,'Airbus',44.51,5950,7.59,'A321','A320 Family',185,16.91,35.8);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (17.28,215260,0.86,375,372,230,'Airbus',67.93,16670,10.69,'A340-500','A340 Family',293,27.59,63.45);
INSERT INTO `mas`.`AIRCRAFTTYPE`(`HEIGHTINM`,`MAXFUELCAPACITY`,`MAXMACHNO`,`MAXSEATING`,`MAXTAKEOFFWEIGHT`,`MAXZEROFUELWEIGHT`,`MFDBY`,`OVERALLLENGTHINM`,`RANGEINKM`,`TRACKINM`,`TYPECODE`,`TYPEFAMILY`,`TYPICALSEATING`,`WHEELBASEINM`,`WINGSPANINM`) VALUES (16.8,155040,0.86,null,275,169,'Airbus',59.4,12400,10.69,'A340-200','A340 Family',261,23.24,60.3);

INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Australia","AU");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Bangladesh","BD");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Brazil","BR");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Brunei","BN");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("China","CN");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Denmark","DK");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("France","FR");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Germany","DE");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Greece","GR");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Hong Kong","HK");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("India","IN");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Indonesia","ID");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Iran","IR");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Italy","IT");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Japan","JP");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Macau","MO");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Malaysia","MY");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Maldives","MV");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Myanmar","MM");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Netherlands","NL");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("New Zealand","NZ");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Philippines","PH");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Russia","RU");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Saudi Arabia","SA");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Singapore","SG");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("South Africa","ZA");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Spain","ES");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Sri Lanka","LK");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Switzerland","CH");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Taiwan","TW");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Thailand","TH");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Turkey","TR");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("United Arab Emirates","AE");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("United Kingdom","GB");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("United States","US");
INSERT INTO `mas`.`COUNTRY`(`COUNTRYNAME`,`ISOCODE`) VALUES("Vietnam","VN");

SET SQL_SAFE_UPDATES = 0;
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Adelaide',9.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia') WHERE CITYNAME='Adelaide';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Brisbane',10);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia') WHERE CITYNAME='Brisbane';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Melbourne',10);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia') WHERE CITYNAME='Melbourne';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Perth',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia') WHERE CITYNAME='Perth';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Sydney',10);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia') WHERE CITYNAME='Sydney';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Dhaka',6);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Bangladesh') WHERE CITYNAME='Dhaka';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Sao Paulo',-3);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Brazil') WHERE CITYNAME='Sao Paulo';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Brunei',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Brunei') WHERE CITYNAME='Brunei';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Yangon',6.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Myanmar') WHERE CITYNAME='Yangon';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Copenhagen',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Denmark') WHERE CITYNAME='Copenhagen';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Paris',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='France') WHERE CITYNAME='Paris';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Munich',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Germany') WHERE CITYNAME='Munich';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Frankfurt',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Germany') WHERE CITYNAME='Frankfurt';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Athens',3);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Greece') WHERE CITYNAME='Athens';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Mumbai',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Mumbai';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Kolkata',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Kolkata';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Delhi',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Delhi';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Chennai',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Chennai';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Bangalore',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Bangalore';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Ahmedabad',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India') WHERE CITYNAME='Ahmedabad';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Jakarta',7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia') WHERE CITYNAME='Jakarta';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Denpasar',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia') WHERE CITYNAME='Denpasar';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Surabaya',7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia') WHERE CITYNAME='Surabaya';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Tehran',5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Iran') WHERE CITYNAME='Tehran';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Rome',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Italy') WHERE CITYNAME='Rome';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Milan',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Italy') WHERE CITYNAME='Milan';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Macau',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Macau') WHERE CITYNAME='Macau';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Hong Kong',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Hong Kong') WHERE CITYNAME='Hong Kong';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Fukuoka',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Fukuoka';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Nagoya',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Nagoya';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Naha',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Naha';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Osaka',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Osaka';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Sapporo',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Sapporo';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Tokyo',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan') WHERE CITYNAME='Tokyo';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Seoul',9);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Korea') WHERE CITYNAME='Seoul';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Kuala Lumpur',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Malaysia') WHERE CITYNAME='Kuala Lumpur';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Male',5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Maldives') WHERE CITYNAME='Male';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Amsterdam',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Netherlands') WHERE CITYNAME='Amsterdam';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Auckland',12);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='New Zealand') WHERE CITYNAME='Auckland';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Christchurch',-12);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='New Zealand') WHERE CITYNAME='Christchurch';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Shanghai',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China') WHERE CITYNAME='Shanghai';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Guangzhou',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China') WHERE CITYNAME='Guangzhou';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Beijing',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China') WHERE CITYNAME='Beijing';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Manila',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Philippines') WHERE CITYNAME='Manila';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Cebu',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Philippines') WHERE CITYNAME='Cebu';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Moscow',3);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Russia') WHERE CITYNAME='Moscow';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Jeddah',3);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Saudi Arabia') WHERE CITYNAME='Jeddah';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Singapore',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Singapore') WHERE CITYNAME='Singapore';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Johannesburg',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Africa') WHERE CITYNAME='Johannesburg';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Durban',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Africa') WHERE CITYNAME='Durban';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('cape town',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='south Africa') WHERE CITYNAME='cape town';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Barcelona',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Spain') WHERE CITYNAME='Barcelona';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Colombo',5.5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Sri Lanka') WHERE CITYNAME='Colombo';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Zurich',2);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Switzerland') WHERE CITYNAME='Zurich';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Taipei',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Taiwan') WHERE CITYNAME='Taipei';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Kaohsiung',8);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Taiwan') WHERE CITYNAME='Kaohsiung';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Bangkok',7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Thailand') WHERE CITYNAME='Bangkok';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Istanbul',3);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Turkey') WHERE CITYNAME='Istanbul';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Dubai',4);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Arab Emirates') WHERE CITYNAME='Dubai';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Manchester',1);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom') WHERE CITYNAME='Manchester';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('London',1);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom') WHERE CITYNAME='London';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Hanoi',7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Vietnam') WHERE CITYNAME='Hanoi';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Ho Chi Minh City',7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Vietnam') WHERE CITYNAME='Ho Chi Minh City';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Chicago',-5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States') WHERE CITYNAME='Chicago';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Houston',-5);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States') WHERE CITYNAME='Houston';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('Los Angeles',-7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States') WHERE CITYNAME='Los Angeles';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('New York',-4);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States') WHERE CITYNAME='New York';
INSERT INTO `mas`.`CITY`(`CITYNAME`,`UTC`) VALUES('San Francisco',-7);
UPDATE `mas`.`CITY` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States') WHERE CITYNAME='San Francisco';

INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('ADL','YPAD',-34.945,138.530502,20,0,'Adelaide Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Adelaide') WHERE IATACODE='ADL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BNE','YBBN',-27.3841,153.117493,13,0,'Brisbane Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Brisbane') WHERE IATACODE='BNE';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MEL','YMML',-37.673302,144.843307,434,0,'Melbourne Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Melbourne') WHERE IATACODE='MEL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('AVV','YMAV',-38.039398,144.469406,35,0,'Melbourne Avalon Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Melbourne') WHERE IATACODE='AVV';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('PER','YPPH',-31.940201,115.966904,67,0,'Perth Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Perth') WHERE IATACODE='PER';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('SYD','YSSY',-33.946098,151.1772,21,0,'Sydney Kingsford Smith Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Australia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Sydney') WHERE IATACODE='SYD';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DAC','VGHS',23.84333,90.397781,30,0,'Dhaka Shahjalal International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Bangladesh'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Dhaka') WHERE IATACODE='DAC';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('GRU','SBGR',-23.431999,-46.469501,2459,0,'Sao Paulo Guarulhos International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Brazil'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Sao Paulo') WHERE IATACODE='GRU';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BWN','WBSB',4.9442,114.928299,73,0,'Brunei International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Brunei'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Brunei') WHERE IATACODE='BWN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('RGN','VYYY',16.907301,96.133217,109,0,'Yangon International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Myanmar'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Yangon') WHERE IATACODE='RGN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CPH','EKCH',55.617908,12.65597,17,0,'Copenhagen Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Denmark'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Copenhagen') WHERE IATACODE='CPH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('XCR','LFOK',48.759998,4.2,587,0,'Paris Vatry Chalons Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='France'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Paris') WHERE IATACODE='XCR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LBG','LFPB',48.958801,2.4336,217,0,'Paris Le Bourget Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='France'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Paris') WHERE IATACODE='LBG';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BVA','LFOB',49.454441,2.112778,359,0,'Paris Beauvais-Tille Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='France'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Paris') WHERE IATACODE='BVA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MUC','EDDM',48.353779,11.78608,1487,0,'Munich Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Germany'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Munich') WHERE IATACODE='MUC';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('FRA','EDDF',50.026421,8.543125,364,0,'Frankfurt Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Germany'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Frankfurt') WHERE IATACODE='FRA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('ATH','LGAV',37.936352,23.94446,308,0,'Athens Eleftherios Venizelos');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Greece'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Athens') WHERE IATACODE='ATH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BOM','VABB',19.08868,72.867912,37,0,'Mumbai Chhatrapati Shivaji International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Mumbai') WHERE IATACODE='BOM';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CCU','VECC',22.65473,88.446716,16,0,'Kolkata International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Kolkata') WHERE IATACODE='CCU';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DEL','VIDP',28.5665,77.103081,777,0,'Delhi Indira Gandhi International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Delhi') WHERE IATACODE='DEL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MAA','VOMM',12.99441,80.180511,52,0,'Chennai International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Chennai') WHERE IATACODE='MAA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BLR','VOBL',13.198889,77.705559,3002,0,'Bangalore Kempegowda International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Bangalore') WHERE IATACODE='BLR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('AMD','VAAH',23.07724,72.634651,189,0,'Ahmedabad Sardar Vallabhbhai Patel International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='India'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Ahmedabad') WHERE IATACODE='AMD';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HLP','WIHH',-6.2666,106.891098,84,0,'Jakarta Halim Perdanakusuma Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Jakarta') WHERE IATACODE='HLP';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DPS','WADD',-8.74816,115.167099,14,0,'Denpasar International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Denpasar') WHERE IATACODE='DPS';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('SUB','WARR',-7.37983,112.786797,9,0,'Surabaya Juanda International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Indonesia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Surabaya') WHERE IATACODE='SUB';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('THR','OIII',35.689159,51.313412,3962,0,'Tehran Mehrabad International Airport_');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Iran'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Tehran') WHERE IATACODE='THR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CIA','LIRA',41.799358,12.59493,427,0,'Rome Ciampino Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Italy'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Rome') WHERE IATACODE='CIA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MXP','LIMC',45.6306,8.728111,767,0,'Milan Malpensa Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Italy'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Milan') WHERE IATACODE='MXP';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BGY','LIME',45.673882,9.704166,782,0,'Milan Bergamo Il Caravaggio International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Italy'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Milan') WHERE IATACODE='BGY';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MFM','VMMC',22.149549,113.591499,20,0,'Macau International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Macau'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Macau') WHERE IATACODE='MFM';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HKG','VHHH',22.30888,113.914703,28,0,'Hong Kong International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Hong Kong'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Hong Kong') WHERE IATACODE='HKG';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('FUK','RJFF',33.585941,130.450607,32,0,'Fukuoka Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Fukuoka') WHERE IATACODE='FUK';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('NGO','RJGG',34.85841,136.805405,15,0,'Nagoya Chubu Centrair International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Nagoya') WHERE IATACODE='NGO';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('OKA','ROAH',26.19581,127.645798,12,0,'Naha Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Naha') WHERE IATACODE='OKA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('ITM','RJOO',34.785519,135.438202,50,0,'Osaka International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Osaka') WHERE IATACODE='ITM';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CTS','RJCC',42.7752,141.6922,82,0,'Sapporo New Chitose Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Sapporo') WHERE IATACODE='CTS';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HND','RJTT',35.55225,139.779602,21,0,'Tokyo Haneda International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Tokyo') WHERE IATACODE='HND';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('NRT','RJAA',35.764721,140.386307,135,0,'Tokyo Narita International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Japan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Tokyo') WHERE IATACODE='NRT';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('ICN','RKSI',37.46907,126.4505,23,0,'Seoul Incheon International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Korea'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Seoul') WHERE IATACODE='ICN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('KUL','WMKK',2.745578,101.7099,69,0,'Kuala Lumpur International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Malaysia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Kuala Lumpur') WHERE IATACODE='KUL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MLE','VRMM',4.191833,73.529121,6,0,'Male Ibrahim Nasir International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Maldives'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Male') WHERE IATACODE='MLE';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('AMS','EHAM',52.308609,4.763889,11,0,'Amsterdam Schiphol Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Netherlands'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Amsterdam') WHERE IATACODE='AMS';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('AKL','NZAA',-37.007999,174.791595,23,0,'Auckland Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='New Zealand'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Auckland') WHERE IATACODE='AKL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CHC','NZCH',-43.489399,172.534393,123,0,'Christchurch International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='New Zealand'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Christchurch') WHERE IATACODE='CHC';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('PVG','ZSPD',31.14337,121.805199,13,0,'Shanghai Pudong International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Shanghai') WHERE IATACODE='PVG';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CAN','ZGGG',23.392429,113.298698,50,0,'Guangzhou Baiyun International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Guangzhou') WHERE IATACODE='CAN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('PEK','ZBAA',40.080109,116.584503,116,0,'Beijing Capital International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='China'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Beijing') WHERE IATACODE='PEK';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MNL','RPLL',14.50864,121.019501,75,0,'Manila Ninoy Aquino International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Philippines'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Manila') WHERE IATACODE='MNL';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CEB','RPVM',10.30754,123.979401,31,0,'Cebu Mactan International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Philippines'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Cebu') WHERE IATACODE='CEB';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('VKO','UUWW',55.59153,37.261478,685,0,'Moscow Vnukovo International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Russia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Moscow') WHERE IATACODE='VKO';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('JED','OEJN',21.67956,39.156528,48,0,'Jeddah King Abdulaziz International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Saudi Arabia'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Jeddah') WHERE IATACODE='JED';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('SIN','WSSS',1.350189,103.9944,22,0,'Singapore Changi Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Singapore'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Singapore') WHERE IATACODE='SIN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HLA','FALA',-25.938499,27.92613,4517,0,'Johannesburg Lanseria International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Africa'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Johannesburg') WHERE IATACODE='HLA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DUR','FALE',-29.616667,31.108334,304,0,'Durban King Shaka International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='South Africa'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Durban') WHERE IATACODE='DUR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CPT','FACT',-33.964802,18.60166,151,0,'Cape Town International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='south Africa'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='cape town') WHERE IATACODE='CPT';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BCN','LEBL',41.29707,2.078463,12,0,'Barcelona El Prat Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Spain'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Barcelona') WHERE IATACODE='BCN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('CMB','VCBI',7.180756,79.884109,30,0,'Colombo Bandaranaike International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Sri Lanka'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Colombo') WHERE IATACODE='CMB';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('ZRH','LSZH',47.464722,8.549167,1416,0,'Zurich Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Switzerland'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Zurich') WHERE IATACODE='ZRH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('TPE','RCTP',25.07773,121.232803,106,0,'Taiwan Taoyuan International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Taiwan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Taipei') WHERE IATACODE='TPE';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('KHH','RCKH',22.577089,120.349998,31,0,'Kaohsiung International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Taiwan'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Kaohsiung') WHERE IATACODE='KHH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DMK','VTBD',13.9125,100.606697,9,0,'Bangkok Don Mueang International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Thailand'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Bangkok') WHERE IATACODE='DMK';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('IST','LTBA',40.976921,28.8146,163,0,'Istanbul Ataturk International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Turkey'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Istanbul') WHERE IATACODE='IST';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('DXB','OMDB',25.252769,55.364441,62,0,'Dubai International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Arab Emirates'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Dubai') WHERE IATACODE='DXB';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MAN','EGCC',53.353741,-2.27495,257,0,'Manchester Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Manchester') WHERE IATACODE='MAN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('STN','EGSS',51.884998,0.235,348,0,'London Stansted Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='London') WHERE IATACODE='STN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('BQH','EGKB',51.33083,0.0325,598,0,'London Biggin Hill Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='London') WHERE IATACODE='BQH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LCY','EGLC',51.505268,0.055278,19,0,'London City Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='London') WHERE IATACODE='LCY';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LHR','EGLL',51.477501,-0.46138,83,0,'London Heathrow Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='London') WHERE IATACODE='LHR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LTN','EGGW',51.874722,-0.36833,526,0,'London Luton Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United Kingdom'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='London') WHERE IATACODE='LTN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HAN','VVNB',21.221189,105.807098,39,0,'Hanoi Noi Bai International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Vietnam'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Hanoi') WHERE IATACODE='HAN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('SGN','VVNA',10.81879,6.651802,33,0,'Tan Son Nhat International Airport_');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='Vietnam'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Ho Chi Minh City') WHERE IATACODE='SGN';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('MDW','KMDW',41.785969,-87.752403,619,0,'Chicago Midway International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Chicago') WHERE IATACODE='MDW';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('RFD','KRFD',42.195278,-89.097221,742,0,'Chicago Rockford International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Chicago') WHERE IATACODE='RFD';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('IAH','KIAH',29.98443,-95.3414,96,0,'Houston George Bush Intercontinental Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Houston') WHERE IATACODE='IAH';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('HOU','KHOU',29.645411,-95.278801,46,0,'Houston William P. Hobby Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Houston') WHERE IATACODE='HOU';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LAX','KLAX',33.94252,-118.406998,125,0,'Los Angeles International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='Los Angeles') WHERE IATACODE='LAX';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('EWR','KEWR',40.692501,-74.168602,18,0,'New York Newark Liberty International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='New York') WHERE IATACODE='EWR';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('LGA','KLGA',40.777248,-73.872597,21,0,'New York LaGuardia Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='New York') WHERE IATACODE='LGA';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('JFK','KJFK',40.639751,-73.7789,14,0,'New York John F. Kennedy International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='New York') WHERE IATACODE='JFK';
INSERT INTO `mas`.`AIRPORT`(`IATACODE`,`ICAOCODE`,`LATITUDE`,`LONGITUDE`,`ALTITUDE`,`ISHUB`,`AIRPORTNAME`) VALUES('SFO','KSFO',37.618969,-122.374001,13,0,'San Francisco International Airport');
UPDATE `mas`.`AIRPORT` SET COUNTRY_ID=(SELECT ID FROM COUNTRY WHERE COUNTRYNAME='United States'), CITY_ID=(SELECT ID FROM CITY WHERE CITYNAME='San Francisco') WHERE IATACODE='SFO';

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.00','0.5000');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.01','0.5040');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.02','0.5080');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.03','0.5120');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.04','0.5160');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.05','0.5199');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.06','0.5239');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.07','0.5279');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.08','0.5319');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.09','0.5359');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.10','0.5398');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.11','0.5438');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.12','0.5478');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.13','0.5517');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.14','0.5557');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.15','0.5596');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.16','0.5636');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.17','0.5675');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.18','0.5714');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.19','0.5753');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.20','0.5793');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.21','0.5832');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.22','0.5871');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.23','0.5910');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.24','0.5948');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.25','0.5987');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.26','0.6026');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.27','0.6064');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.28','0.6103');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.29','0.6141');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.30','0.6179');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.31','0.6217');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.32','0.6255');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.33','0.6293');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.34','0.6331');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.35','0.6368');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.36','0.6406');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.37','0.6443');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.38','0.6480');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.39','0.6517');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.40','0.6554');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.41','0.6591');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.42','0.6628');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.43','0.6664');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.44','0.6700');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.45','0.6736');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.46','0.6772');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.47','0.6808');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.48','0.6844');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.49','0.6879');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.50','0.6915');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.51','0.6950');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.52','0.6985');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.53','0.7019');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.54','0.7054');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.55','0.7088');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.56','0.7123');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.57','0.7157');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.58','0.7190');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.59','0.7224');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.60','0.7257');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.61','0.7291');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.62','0.7324');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.63','0.7357');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.64','0.7389');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.65','0.7422');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.66','0.7454');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.67','0.7486');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.68','0.7517');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.69','0.7549');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.70','0.7580');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.71','0.7611');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.72','0.7642');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.73','0.7673');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.74','0.7704');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.75','0.7734');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.76','0.7764');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.77','0.7794');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.78','0.7823');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.79','0.7852');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.80','0.7881');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.81','0.7910');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.82','0.7939');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.83','0.7967');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.84','0.7995');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.85','0.8023');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.86','0.8051');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.87','0.8078');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.88','0.8106');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.89','0.8133');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.90','0.8159');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.91','0.8186');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.92','0.8212');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.93','0.8238');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.94','0.8264');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.95','0.8289');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.96','0.8315');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.97','0.8340');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.98','0.8365');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '0.99','0.8389');


INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.00','0.8413');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.01','0.8438');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.02','0.8461');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.03','0.8485');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.04','0.8508');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.05','0.8531');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.06','0.8554');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.07','0.8577');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.08','0.8599');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.09','0.8621');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.10','0.8643');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.11','0.8665');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.12','0.8686');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.13','0.8708');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.14','0.8729');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.15','0.8749');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.16','0.8770');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.17','0.8790');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.18','0.8810');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.19','0.8830');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.20','0.8849');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.21','0.8869');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.22','0.8888');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.23','0.8907');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.24','0.8925');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.25','0.8944');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.26','0.8962');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.27','0.8980');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.28','0.8997');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.29','0.9015');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.30','0.9032');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.31','0.9049');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.32','0.9066');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.33','0.9082');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.34','0.9099');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.35','0.9115');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.36','0.9131');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.37','0.9147');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.38','0.9162');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.39','0.9177');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.40','0.9192');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.41','0.9207');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.42','0.9222');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.43','0.9236');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.44','0.9251');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.45','0.9265');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.46','0.9279');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.47','0.9292');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.48','0.9306');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.49','0.9319');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.50','0.9332');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.51','0.9345');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.52','0.9357');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.53','0.9370');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.54','0.9382');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.55','0.9394');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.56','0.9406');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.57','0.9418');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.58','0.9429');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.59','0.9441');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.60','0.9452');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.61','0.9463');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.62','0.9474');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.63','0.9484');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.64','0.9495');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.65','0.9505');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.66','0.9515');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.67','0.9525');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.68','0.9535');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.69','0.9545');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.70','0.9554');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.71','0.9564');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.72','0.9573');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.73','0.9582');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.74','0.9591');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.75','0.9599');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.76','0.9608');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.77','0.9616');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.78','0.9625');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.79','0.9633');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.80','0.9641');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.81','0.9649');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.82','0.9656');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.83','0.9664');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.84','0.9671');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.85','0.9678');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.86','0.9686');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.87','0.9693');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.88','0.9699');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.89','0.9706');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.90','0.9713');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.91','0.9719');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.92','0.9726');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.93','0.9732');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.94','0.9738');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.95','0.9744');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.96','0.9750');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.97','0.9756');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.98','0.9761');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '1.99','0.9767');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.00','0.9772');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.01','0.9778');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.02','0.9783');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.03','0.9788');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.04','0.9793');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.05','0.9798');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.06','0.9803');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.07','0.9808');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.08','0.9812');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.09','0.9817');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.10','0.9821');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.11','0.9826');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.12','0.9830');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.13','0.9834');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.14','0.9838');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.15','0.9842');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.16','0.9846');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.17','0.9850');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.18','0.9854');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.19','0.9857');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.20','0.9861');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.21','0.9864');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.22','0.9868');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.23','0.9871');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.24','0.9875');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.25','0.9878');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.26','0.9881');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.27','0.9884');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.28','0.9887');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.29','0.9890');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.30','0.9893');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.31','0.9896');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.32','0.9898');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.33','0.9901');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.34','0.9904');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.35','0.9906');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.36','0.9909');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.37','0.9911');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.38','0.9913');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.39','0.9916');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.40','0.9918');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.41','0.9920');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.42','0.9922');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.43','0.9925');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.44','0.9927');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.45','0.9929');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.46','0.9931');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.47','0.9932');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.48','0.9934');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.49','0.9936');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.50','0.9938');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.51','0.9940');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.52','0.9941');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.53','0.9943');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.54','0.9945');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.55','0.9946');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.56','0.9948');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.57','0.9949');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.58','0.9951');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.59','0.9952');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.60','0.9953');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.61','0.9955');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.62','0.9956');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.63','0.9957');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.64','0.9959');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.65','0.9960');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.66','0.9961');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.67','0.9962');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.68','0.9963');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.69','0.9964');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.70','0.9965');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.71','0.9966');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.72','0.9967');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.73','0.9968');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.74','0.9969');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.75','0.9970');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.76','0.9971');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.77','0.9972');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.78','0.9973');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.79','0.9974');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.80','0.9974');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.81','0.9975');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.82','0.9976');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.83','0.9977');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.84','0.9977');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.85','0.9978');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.86','0.9979');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.87','0.9979');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.88','0.9980');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.89','0.9981');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.90','0.9981');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.91','0.9982');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.92','0.9982');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.93','0.9983');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.94','0.9984');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.95','0.9984');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.96','0.9985');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.97','0.9985');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.98','0.9986');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '2.99','0.9986');

INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.00','0.9987');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.01','0.9987');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.02','0.9987');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.03','0.9988');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.04','0.9988');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.05','0.9989');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.06','0.9989');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.07','0.9989');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.08','0.9990');
INSERT INTO `mas`.`NORMALDISTRIBUTION` (`DELETED`,`ZSCORE`,`P`)
VALUES(0, '3.09','0.9990');