INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('admin', 'admin');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user1', 'user1');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user2', 'user2');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user3', 'user3');