INSERT INTO SYSTEMUSER (USERNAME, PASSWORD, EMAIL) VALUES('admin', 'admin','a0119405@u.nus.edu');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD, EMAIL) VALUES('user1', 'user1','wingalong@gmail.com');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user2', 'user2');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user3', 'user3');

INSERT INTO SYSTEMROLE (ROLENAME) VALUES('IT Staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Admin');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Pricing Officer');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Sales counter Staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('HR');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Fleet Planner');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Route Planner');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Flight Scheduler');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Cockpit Crew');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Cabin Crew');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Maintenance Staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Product Designer');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Inventory Manager');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Call Center Staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Check-in counter staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Boarding staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Finance department staff');
INSERT INTO SYSTEMROLE (ROLENAME) VALUES('Operations Analyst');

INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Common Infrastructure', 'User Account Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Common Infrastructure', 'User Workspace Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Common Infrastructure', 'Internal Communication Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Planning System', 'Fleet Planning Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Planning System', 'Route Planning Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Planning System', 'Flight Scheduling Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Flight Operation System', 'Flight Crew Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Flight Operation System', 'Pre-flight Sign-in Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Flight Operation System', 'Post-flight Reporting Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Flight Operation System', 'Maintenance Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Inventory System', 'Product Designe Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Inventory System', 'Pricing Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Inventory System', 'Yield Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Reservation System', ' Booking Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Reservation System', ' Payment Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Reservation System', ' Direct Distribution System');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Reservation System', ' Global Distribution System');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Departure Control System', 'Check-in Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Departure Control System', 'Baggage Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Departure Control System', 'Distribution Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Administration System', 'Revenue Accounting Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Administration System', 'Cost Accounting Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Airline Administration System', 'Reporting Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Customer Relationship Management System', 'Profile Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Customer Relationship Management System', 'Customer Loyalty Management Module');
INSERT INTO PERMISSION (SYSTEMMODULE, TITLE) VALUES('Customer Relationship Management System', 'Customer Relationship Management Analystics Module');
