INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('admin', 'password');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user1', 'password');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user2', 'password');
INSERT INTO SYSTEMUSER (USERNAME, PASSWORD) VALUES('user3', 'password');